import OrderBook from "../web/order/book";
import OrderShort from "../web/order/short";
import Purchase from "../web/orderEx/purchase";
import Scrapped from "../web/scrapped/scrapped";

 function Fack(){
    return [
        {
            label:'訂單納入企劃'
            ,path:'order'
            ,items:[
                {
                    path:'book'
                    ,label:'訂單作業'
                    ,element:OrderBook
                }
                ,{
                    path:'short'
                    ,label:'達成率查詢'
                    ,element:OrderShort
                }
            ]
        }
        ,{
            label:'客戶管理'
            ,path:'orderEx'
            ,items:[
                {
                    path:'purchase'
                    ,label:'客戶列表'
                    ,element:Purchase
                    ,desc:'Description...'
                }
            ]
        }        
        ,{
            label:'權限管理'
            ,path:'scrapped'
            ,items:[
                {
                    path:'scrapped'
                    ,label:'功能群組'
                    ,element:Scrapped
                }
            ]
        }
    ]
}

export default function WebRouteConfig(){
    return [
        {
            label:'訂貨業務'
            ,path:'order'
            ,items:[
                {
                    path:'book'
                    ,label:'訂單作業'
                    ,element:OrderBook
                }
                ,{
                    path:'short'
                    ,label:'訂單業務'
                    ,element:OrderShort
                }
            ]
        }
        ,{
            label:'進貨/驗貨/退貨業務'
            ,path:'orderEx'
            ,items:[
                {
                    path:'purchase'
                    ,label:'進貨'
                    ,element:Purchase
                    ,desc:'Description...'
                }
            ]
        }    
        ,{
            label:'庫存業務'
            ,path:'k'
            ,items:[
                {
                    path:'k1'
                    ,label:'庫存業務'
                    ,element:Scrapped
                }
            ]
        }        
        ,{
            label:'營收日報業務'
            ,path:'i'
            ,items:[
                {
                    path:'營收日報業務'
                    ,label:'i1'
                    ,element:Scrapped
                }
            ]
        }        
        ,{
            label:'銷售分析業務'
            ,path:'s'
            ,items:[
                {
                    path:'s1'
                    ,label:'銷售分析業務'
                    ,element:Scrapped
                }
            ]
        }        
        ,{
            label:'會員管理'
            ,path:'m'
            ,items:[
                {
                    path:'m1'
                    ,label:'會員管理'
                    ,element:Scrapped
                }
            ]
        }        
        ,{
            label:'電子發票管理'
            ,path:'c'
            ,items:[
                {
                    path:'c1'
                    ,label:'電子發票管理'
                    ,element:Scrapped
                }
            ]
        }        
        ,{
            label:'即時公告'
            ,path:'n'
            ,items:[
                {
                    path:'n1'
                    ,label:'即時公告'
                    ,element:Scrapped
                }
            ]
        }

    ]
}